[2023-04-01 10:07:10,989] numexpr.utils - INFO - NumExpr defaulting to 8 threads.
[2023-04-01 10:07:14,155] root - INFO - Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\end to end project\\US Visa Prediction\\US Visa Prediction\\us_visa\\artifact')
[2023-04-01 10:07:14,155] root - INFO - Data Ingestion config: DataIngestionConfig(dataset_download_url='https://raw.githubusercontent.com/Shivan118/Main-Branching/main/Visadataset.csv', raw_data_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\end to end project\\US Visa Prediction\\US Visa Prediction\\us_visa\\artifact\\data_ingestion\\2023-04-01-10-07-10\\raw_data', ingested_train_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\end to end project\\US Visa Prediction\\US Visa Prediction\\us_visa\\artifact\\data_ingestion\\2023-04-01-10-07-10\\ingested_data\\train', ingested_test_dir='C:\\Users\\Sumeet Maheshwari\\Desktop\\end to end project\\US Visa Prediction\\US Visa Prediction\\us_visa\\artifact\\data_ingestion\\2023-04-01-10-07-10\\ingested_data\\test')
[2023-04-01 10:07:14,156] root - INFO - >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Data Ingestion log started.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 


[2023-04-01 10:07:14,157] root - INFO - Downloading file from :[https://raw.githubusercontent.com/Shivan118/Main-Branching/main/Visadataset.csv] into :[C:\Users\Sumeet Maheshwari\Desktop\end to end project\US Visa Prediction\US Visa Prediction\us_visa\artifact\data_ingestion\2023-04-01-10-07-10\raw_data\Visadataset.csv]
[2023-04-01 10:07:19,587] root - INFO - File :[C:\Users\Sumeet Maheshwari\Desktop\end to end project\US Visa Prediction\US Visa Prediction\us_visa\artifact\data_ingestion\2023-04-01-10-07-10\raw_data\Visadataset.csv] has been downloaded successfully.
[2023-04-01 10:07:19,587] root - INFO - Reading csv file: [C:\Users\Sumeet Maheshwari\Desktop\end to end project\US Visa Prediction\US Visa Prediction\us_visa\artifact\data_ingestion\2023-04-01-10-07-10\raw_data\Visadataset.csv]
[2023-04-01 10:07:19,649] root - INFO - Splitting data into train and test
[2023-04-01 10:07:19,655] root - INFO - Exporting training dataset to file: [C:\Users\Sumeet Maheshwari\Desktop\end to end project\US Visa Prediction\US Visa Prediction\us_visa\artifact\data_ingestion\2023-04-01-10-07-10\ingested_data\train\Visadataset.csv]
[2023-04-01 10:07:19,734] root - INFO - Exporting test dataset to file: [C:\Users\Sumeet Maheshwari\Desktop\end to end project\US Visa Prediction\US Visa Prediction\us_visa\artifact\data_ingestion\2023-04-01-10-07-10\ingested_data\test\Visadataset.csv]
[2023-04-01 10:07:19,762] root - INFO - Data Ingestion artifact:[DataIngestionArtifact(train_file_path='C:\\Users\\Sumeet Maheshwari\\Desktop\\end to end project\\US Visa Prediction\\US Visa Prediction\\us_visa\\artifact\\data_ingestion\\2023-04-01-10-07-10\\ingested_data\\train\\Visadataset.csv', test_file_path='C:\\Users\\Sumeet Maheshwari\\Desktop\\end to end project\\US Visa Prediction\\US Visa Prediction\\us_visa\\artifact\\data_ingestion\\2023-04-01-10-07-10\\ingested_data\\test\\Visadataset.csv', is_ingested=True, message='Data ingestion completed successfully.')]
[2023-04-01 10:07:19,764] root - ERROR - 
                        error occured in script: 
                        [C:\Users\Sumeet Maheshwari\Desktop\end to end project\US Visa Prediction\US Visa Prediction\visa\pipeline\pipeline.py] at 
                        try block line number: [68] execption block line number: [73]
                        error message: [
                        error occured in script: 
                        [C:\Users\Sumeet Maheshwari\Desktop\end to end project\US Visa Prediction\US Visa Prediction\visa\pipeline\pipeline.py] at 
                        try block line number: [40] execption block line number: [44]
                        error message: [
                        error occured in script: 
                        [C:\Users\Sumeet Maheshwari\Desktop\end to end project\US Visa Prediction\US Visa Prediction\visa\config\Configuartion.py] at 
                        try block line number: [81] execption block line number: [86]
                        error message: [<lambda>() got an unexpected keyword argument 'schema_file_path']]]
